/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.lang.reflect.AccessibleObject;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.sql.Connection;//Conexión a base de datos.
import java.sql.DriverManager;//driver de conexión.
import java.sql.ResultSet;//resultado final de datos.
import java.sql.ResultSetMetaData;//resultado de metadatos.
import java.sql.SQLException;//Tratamiento de errores de BD SQL
import java.sql.Statement;//Generador de sentencias SQL
import java.text.SimpleDateFormat;//Formatear datos
import java.util.Date;//Fecha de sistema
import javax.swing.ImageIcon;//Tratamiento de imágenes
import javax.swing.JOptionPane;//Ventanas emergentes
import javax.swing.table.DefaultTableModel;//tabla de datos
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;
import pojos.piezas;
/**
 *
 * @author Chamanx3
 */
public class CRUD extends javax.swing.JFrame {
 piezas objpiezas=new piezas();
    public Connection cn;
    public Statement stmt;
    public ResultSet rs;
    public CRUD(){initComponents();}
    /**
     * Creates new form CRUD
     */
    public void conectarBase(){
        try{//inicia try
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost/bdgutierrezproyectois","root","");
            JOptionPane.showMessageDialog(null,"Conexion a BD OK\n\nGutierrez Flores");
            stmt=cn.createStatement();//genera sentencias sobre objetos de base de datos
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error de base de datos 1:\n"+ex);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error de base de datos 2:\n"+e);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCapturaGF = new javax.swing.JPanel();
        lbIdGF = new javax.swing.JLabel();
        lbMarcaGF = new javax.swing.JLabel();
        lbModeloGF = new javax.swing.JLabel();
        lbPrecioGF = new javax.swing.JLabel();
        txtIdGF = new javax.swing.JTextField();
        txtMarcaGF = new javax.swing.JTextField();
        txtModeloGF = new javax.swing.JTextField();
        txtPrecioGF = new javax.swing.JTextField();
        btnRegistrarEquipoGF = new javax.swing.JButton();
        btnPDFGF = new javax.swing.JButton();
        lbPrecioGF1 = new javax.swing.JLabel();
        txtestandar = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panEliminar = new javax.swing.JPanel();
        lblCapturaId = new javax.swing.JLabel();
        txtLibroEliminar = new javax.swing.JTextField();
        btnEliminarLibro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panCapturaGF.setBorder(javax.swing.BorderFactory.createTitledBorder("Captura Datos Componente"));
        panCapturaGF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbIdGF.setText("ID:");

        lbMarcaGF.setText("Marca:");

        lbModeloGF.setText("Modelo:");

        lbPrecioGF.setText("Precio");

        txtMarcaGF.setToolTipText("");

        txtPrecioGF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioGFActionPerformed(evt);
            }
        });

        btnRegistrarEquipoGF.setText("Registrar Componente");
        btnRegistrarEquipoGF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEquipoGFActionPerformed(evt);
            }
        });

        btnPDFGF.setText("Ver reporte PDF");
        btnPDFGF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFGFActionPerformed(evt);
            }
        });

        lbPrecioGF1.setText("Estandar");

        txtestandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestandarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panCapturaGFLayout = new javax.swing.GroupLayout(panCapturaGF);
        panCapturaGF.setLayout(panCapturaGFLayout);
        panCapturaGFLayout.setHorizontalGroup(
            panCapturaGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCapturaGFLayout.createSequentialGroup()
                .addGroup(panCapturaGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCapturaGFLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panCapturaGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panCapturaGFLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnRegistrarEquipoGF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panCapturaGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panCapturaGFLayout.createSequentialGroup()
                                    .addComponent(lbPrecioGF1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtestandar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panCapturaGFLayout.createSequentialGroup()
                                    .addComponent(lbModeloGF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtModeloGF))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panCapturaGFLayout.createSequentialGroup()
                                    .addComponent(lbPrecioGF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPrecioGF))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panCapturaGFLayout.createSequentialGroup()
                                    .addComponent(lbMarcaGF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                    .addComponent(txtMarcaGF, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panCapturaGFLayout.createSequentialGroup()
                                    .addComponent(lbIdGF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtIdGF)))))
                    .addGroup(panCapturaGFLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnPDFGF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        panCapturaGFLayout.setVerticalGroup(
            panCapturaGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCapturaGFLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panCapturaGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdGF)
                    .addComponent(txtIdGF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panCapturaGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMarcaGF)
                    .addComponent(txtMarcaGF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panCapturaGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbModeloGF)
                    .addComponent(txtModeloGF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCapturaGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecioGF)
                    .addComponent(txtPrecioGF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panCapturaGFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPrecioGF1)
                    .addComponent(txtestandar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btnRegistrarEquipoGF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnPDFGF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 204));

        lblCapturaId.setText("Catura el ID del componente a eliminar");

        txtLibroEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibroEliminarActionPerformed(evt);
            }
        });

        btnEliminarLibro.setBackground(new java.awt.Color(153, 153, 0));
        btnEliminarLibro.setText("Eliminar componente");
        btnEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panEliminarLayout = new javax.swing.GroupLayout(panEliminar);
        panEliminar.setLayout(panEliminarLayout);
        panEliminarLayout.setHorizontalGroup(
            panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEliminarLayout.createSequentialGroup()
                .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEliminarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCapturaId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLibroEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panEliminarLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnEliminarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panEliminarLayout.setVerticalGroup(
            panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapturaId)
                    .addComponent(txtLibroEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnEliminarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("Eliminar Componente", panEliminar);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Gutierrez Corp Software");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unnamed.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/141013.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(panCapturaGF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62)))
                .addComponent(panCapturaGF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        panCapturaGF.getAccessibleContext().setAccessibleName("Captura Datos Componentes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioGFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioGFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioGFActionPerformed

    private void btnRegistrarEquipoGFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEquipoGFActionPerformed
        conectarBase();

        //Almacenar los valores de formulario en el objeto.
        objpiezas.setIdcomponente(Integer.parseInt(txtIdGF.getText()));
        objpiezas.setMarca(txtMarcaGF.getText());
        objpiezas.setModelo(txtModeloGF.getText());
        objpiezas.setPrecio(Integer.parseInt(txtPrecioGF.getText()));
        objpiezas.setEstandar(txtestandar.getText());
        // Variable objeto para registrar un equipo
        String altaEquipo="INSERT INTO piezas (idcomponente,marca,modelo,precio,estandar) VALUES ('"+objpiezas.getIdcomponente()+"','"+objpiezas.getMarca()+"','"+objpiezas.getModelo()+"','"+objpiezas.getPrecio()+"','"+objpiezas.getEstandar()+"')";
        // Estructura de tratamiento de errores en ejecución.

        try {
            stmt.executeUpdate(altaEquipo);
            JOptionPane.showMessageDialog(null,"Se registró un equipo de forma exitosa.\n\n"+objpiezas.getModelo());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error 1 de base de datos al general alta equipo\n\n Verifica\n\n"+ e);
        }
    }//GEN-LAST:event_btnRegistrarEquipoGFActionPerformed

    private void btnPDFGFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFGFActionPerformed

        conectarBase();
        try {
            String rutaReporte="src/reportes/rtpcomponentes.jasper";
            JasperPrint rtpcomponentes = JasperFillManager.fillReport(rutaReporte,null,cn);
            JasperViewer ventanaVisor = new JasperViewer(rtpcomponentes,false);
            ventanaVisor.setTitle("Reporte de Equipos Gutierrez Corp");
            ventanaVisor.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de BD en informe Verifica\n\n"+e);
        }
    }//GEN-LAST:event_btnPDFGFActionPerformed

    private void txtestandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestandarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestandarActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
        // TODO add your handling code here:

        int confirmaBaja;
        try {
            conectarBase();
            int componentebaja=Integer.parseInt(txtLibroEliminar.getText());

            confirmaBaja=stmt.executeUpdate("DELETE FROM piezas WHERE idcomponente = '"+componentebaja+"' ");

            if (confirmaBaja==1) {
                JOptionPane.showMessageDialog(null, "Se dio de baja el componente de BD\n\n"+componentebaja+"\nVerifica consulta");

            } else {
                JOptionPane.showMessageDialog(null, "Error, no existe Id de componente en BD\n\n"+componentebaja+"\nVerifica consulta");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al procesar baja de BD\n\n"+ex);
        }
    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    private void txtLibroEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibroEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibroEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarLibro;
    private javax.swing.JButton btnPDFGF;
    private javax.swing.JButton btnRegistrarEquipoGF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbIdGF;
    private javax.swing.JLabel lbMarcaGF;
    private javax.swing.JLabel lbModeloGF;
    private javax.swing.JLabel lbPrecioGF;
    private javax.swing.JLabel lbPrecioGF1;
    private javax.swing.JLabel lblCapturaId;
    private javax.swing.JPanel panCapturaGF;
    private javax.swing.JPanel panEliminar;
    private javax.swing.JTextField txtIdGF;
    private javax.swing.JTextField txtLibroEliminar;
    private javax.swing.JTextField txtMarcaGF;
    private javax.swing.JTextField txtModeloGF;
    private javax.swing.JTextField txtPrecioGF;
    private javax.swing.JTextField txtestandar;
    // End of variables declaration//GEN-END:variables
}
